### ISSUE TITLE
Updated English translation

### ISSUE THREAD

**Issue by scrubbless** [EtiCarasoft/22-30-Birds-Shop#1]
Hi Joan (@EtiCarasoft),

I have updated the translation for some of the new events you have created.

I've attached the English Localisation file:
[Localization.English.txt](https://github.com/EtiCarasoft/22-30-Birds-Shop/files/2639150/Localization.English.txt)

Alternatively here is a ZIP of the scenario package files.
[22-30-Birds-Shop.zip](https://github.com/EtiCarasoft/22-30-Birds-Shop/files/2639142/22-30-Birds-Shop.zip)

**Comment by EtiCarasoft** [comment]
Previously I invited you as a collaborator. 

I'll upload the files

**Comment by scrubbless** [comment]
It said I didn't have permissions. I suspect I didn't accept the invite in time, looks like it might have expired.

**Comment by scrubbless** [comment]
Hi Joan (@EtiCarasoft)

I missed some events in the latest translation, I think I have gotten them all now - if you notice any let me know:

[Localization.English.txt](https://github.com/EtiCarasoft/22-30-Birds-Shop/files/2640291/Localization.English.txt)

**Comment by BenRQ** [comment]
Update is done :)

**Comment by scrubbless** [comment]
Hi @EtiCarasoft or @BenRQ 

I have corrected yet more spelling mistakes and grammar errors. I apologise, I am terrible at proof reading it seems!

My favourite mess up with translation yet....
![image](https://user-images.githubusercontent.com/32058089/49673809-9ef17580-fa67-11e8-8c3c-23386eef518d.png)
**no shit!**

Anyway here is the new file:
[Localization.English.txt](https://github.com/EtiCarasoft/22-30-Birds-Shop/files/2658834/Localization.English.txt)
