### ISSUE TITLE
Updated English translation #2

### ISSUE THREAD

**Issue by scrubbless** [EtiCarasoft/22-30-Birds-Shop#2]
Hi @EtiCarasoft or @BenRQ

I have corrected yet more spelling mistakes and grammar errors. I apologise, I am terrible at proof reading it seems!

My favourite mess up with translation yet....
![image](https://user-images.githubusercontent.com/32058089/49673809-9ef17580-fa67-11e8-8c3c-23386eef518d.png)
**Oh shit! Creepy**

Anyway here is the new file:
[Localization.English.txt](https://github.com/EtiCarasoft/22-30-Birds-Shop/files/2658834/Localization.English.txt)

_Originally posted by @scrubbless in https://github.com/EtiCarasoft/22-30-Birds-Shop/issues/1#issuecomment-445372163_

**Comment by BenRQ** [comment]
It's done
